services:
    PayReckoner\Infrastructure\Storage\RedisConnectionFactory:
        arguments:
            $host: '%redis.host%'
            $port: '%redis.port%'
            $database: '%redis.database%'

    PayReckoner\Infrastructure\Storage\RedisRecordStorage:
        arguments:
            - '@PayReckoner\Infrastructure\Storage\RedisConnectionFactory'

    PayReckoner\Application\Service\FixtureGenerator: ~

    PayReckoner\Application\Command\RunPipelineCommand: ~

    PayReckoner\Application\Command\GenerateFixturesCommand:
        arguments:
            - '@PayReckoner\Application\Service\FixtureGenerator'
            - '@PayReckoner\Infrastructure\Storage\RedisRecordStorage'
