imports:
    - { resource: 'redis.yaml' }

services:
    PayReckoner\Infrastructure\Storage\Redis\RedisConnectionFactory:
        arguments:
            $host: '%redis.host%'
            $port: '%redis.port%'
            $database: '%redis.database%'

    PayReckoner\Infrastructure\Storage\Redis\RedisRecordStorage:
        arguments:
            - '@PayReckoner\Infrastructure\Storage\Redis\RedisConnectionFactory'

    PayReckoner\Application\Service\Fixtures\TransactionFixtureGenerator: ~

    PayReckoner\Application\Service\Fixtures\FeeRuleFixtureGenerator: ~

    PayReckoner\Application\Service\Fixtures\FixtureGenerator:
        arguments:
            - '@PayReckoner\Application\Service\Fixtures\TransactionFixtureGenerator'
            - '@PayReckoner\Application\Service\Fixtures\FeeRuleFixtureGenerator'

    PayReckoner\Application\Command\RunPipelineCommand: ~

    PayReckoner\Application\Command\GenerateFixturesCommand:
        arguments:
            - '@PayReckoner\Application\Service\Fixtures\FixtureGenerator'
            - '@PayReckoner\Infrastructure\Storage\Redis\RedisRecordStorage'
